import os
import json

from dotenv import load_dotenv
from google import genai


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

if not API_KEY:
    raise Exception("GEMINI_API_KEY not found in .env file")


# ============================================================
# CREATE GEMINI CLIENT
# ============================================================

client = genai.Client(api_key=API_KEY)


# ============================================================
# PROJECT DETAILS BACKUP
# ============================================================

def get_backup_project_details(project_title: str, project_type: str):

    return {
        "projectName": project_title,
        "domain": "Computer Science & Information Technology",
        "projectType": project_type,
        "difficulty": "Medium",
        "progress": 0,
        "estimatedDuration": "6 Weeks",
        "teamSize": "2-4 Students",

        "description": (
            f"{project_title} is a college-level software project "
            "designed to provide a practical solution to a real-world "
            "problem. The system can be developed as a student project "
            "using commonly available programming technologies."
        ),

        "technologies": [
            "Flutter",
            "Dart",
            "Python",
            "FastAPI",
            "SQLite",
            "VS Code"
        ],

        "modules": [
            {
                "name": "User Management",
                "description": (
                    "Allows users to register, log in and manage "
                    "their basic application information."
                )
            },
            {
                "name": "Project Dashboard",
                "description": (
                    "Provides a central dashboard where users can "
                    "access the main features of the application."
                )
            },
            {
                "name": "Core Project Module",
                "description": (
                    "Contains the primary functionality required "
                    "to solve the selected project problem."
                )
            },
            {
                "name": "Data Management",
                "description": (
                    "Stores, retrieves and manages application "
                    "data using a database."
                )
            },
            {
                "name": "Reports & Results",
                "description": (
                    "Displays useful results, summaries and "
                    "information generated by the system."
                )
            }
        ],

        "skills": [
            "Flutter Development",
            "Dart Programming",
            "Python Programming",
            "FastAPI REST API Development",
            "Database Management",
            "UI/UX Design",
            "API Integration"
        ],

        "roadmap": [
            {
                "phase": "Requirements & Planning",
                "duration": "1 Week",
                "tasks": [
                    "Understand the project problem.",
                    "Define project objectives and requirements.",
                    "Design the basic system architecture.",
                    "Prepare the database structure."
                ]
            },
            {
                "phase": "UI/UX Development",
                "duration": "1 Week",
                "tasks": [
                    "Create the application screens.",
                    "Design navigation between screens.",
                    "Create reusable Flutter widgets.",
                    "Build the basic user interface."
                ]
            },
            {
                "phase": "Backend Development",
                "duration": "1 Week",
                "tasks": [
                    "Set up the FastAPI backend.",
                    "Create required API endpoints.",
                    "Connect the database.",
                    "Implement basic data operations."
                ]
            },
            {
                "phase": "Core Feature Development",
                "duration": "1.5 Weeks",
                "tasks": [
                    "Implement the main project functionality.",
                    "Connect Flutter with the backend APIs.",
                    "Implement required data processing.",
                    "Handle errors and invalid inputs."
                ]
            },
            {
                "phase": "Testing & Improvements",
                "duration": "1 Week",
                "tasks": [
                    "Test all major features.",
                    "Fix bugs and API errors.",
                    "Improve UI and user experience.",
                    "Test different input conditions."
                ]
            },
            {
                "phase": "Final Deployment & Presentation",
                "duration": "0.5 Week",
                "tasks": [
                    "Prepare the final application.",
                    "Create project documentation.",
                    "Prepare screenshots and diagrams.",
                    "Prepare the final project demonstration."
                ]
            }
        ],

        "recommendations": [
            "Keep the first version of the project simple and functional.",
            "Use modular code so additional features can be added later.",
            "Validate user inputs before sending them to the backend.",
            "Test the application thoroughly before the final demonstration.",
            "Keep a backup copy of the project before making major changes."
        ]
    }


# ============================================================
# PROJECT DETAILS GENERATOR
# ============================================================

def generate_project_details(project_title: str, project_type: str):

    json_format = """
{
    "projectName": "",
    "domain": "",
    "projectType": "",
    "difficulty": "",
    "progress": 0,
    "estimatedDuration": "",
    "teamSize": "",
    "description": "",
    "technologies": [],
    "modules": [
        {
            "name": "",
            "description": ""
        }
    ],
    "skills": [],
    "roadmap": [
        {
            "phase": "",
            "duration": "",
            "tasks": []
        }
    ],
    "recommendations": []
}
"""

    prompt = f"""
You are an experienced software engineer and academic project mentor.

Your job is to help BE, BTech, BCA, MCA and Diploma students.

Project Title:
{project_title}

Project Type:
{project_type}

Generate a realistic college-level software project.

Rules:

1. Suitable for engineering students.

2. Team Size:
   2-4 Students

3. Duration:
   4-8 Weeks

4. Prefer technologies like:

- Flutter
- Dart
- Python
- FastAPI
- Firebase
- MySQL
- MongoDB
- HTML
- CSS
- JavaScript
- React
- Node.js
- Android Studio
- VS Code

Avoid enterprise technologies like:

- Kubernetes
- Kafka
- RabbitMQ
- Keycloak
- SAP

unless absolutely required.

Generate:

- Project Name
- Domain
- Difficulty
- Description
- Technologies
- Modules
- Skills
- Development Roadmap
- Recommendations

Roadmap should contain 5 or 6 phases.

Each roadmap phase should include:

- phase
- duration
- tasks

Modules should include:

- name
- description

Progress should always be 0.

Return ONLY valid JSON.

Use this JSON structure:

{json_format}
"""

    try:

        print("Trying Gemini Project Details Generator...")

        response = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=prompt,
        )

        text = response.text.strip()

        # Remove Markdown code block
        if text.startswith("```"):
            text = text.replace("```json", "")
            text = text.replace("```", "")
            text = text.strip()

        data = json.loads(text)

        print("Gemini Project Details generated successfully.")

        return data

    except Exception as e:

        print("Gemini Project Details Error:")
        print(e)

        print("Using BACKUP Project Details.")

        return get_backup_project_details(
            project_title,
            project_type
        )


# ============================================================
# IDEA GENERATOR BACKUP
# ============================================================

def get_backup_ideas(field: str, level: str):

    backup_ideas = {

        "AI": [
            {
                "title": "AI Study Assistant",
                "description": (
                    "An intelligent study assistant that helps "
                    "students organize study materials and receive "
                    "basic academic support."
                )
            },
            {
                "title": "Smart Attendance System",
                "description": (
                    "A system that helps educational institutions "
                    "record attendance and generate useful reports."
                )
            },
            {
                "title": "Student Performance Analyzer",
                "description": (
                    "A system that analyzes student marks and "
                    "provides useful performance summaries."
                )
            },
            {
                "title": "AI Resume Assistant",
                "description": (
                    "An application that helps students organize "
                    "their resume information and improve their "
                    "professional profile."
                )
            },
            {
                "title": "College FAQ Assistant",
                "description": (
                    "An intelligent assistant that provides answers "
                    "to frequently asked college-related questions."
                )
            }
        ],

        "Medical": [
            {
                "title": "Medicine Reminder System",
                "description": (
                    "An application that reminds users about "
                    "scheduled medicines and maintains basic "
                    "medication records."
                )
            },
            {
                "title": "Hospital Appointment System",
                "description": (
                    "A system for managing doctor appointments "
                    "and basic patient information."
                )
            },
            {
                "title": "Health Record Manager",
                "description": (
                    "An application for organizing basic health "
                    "records and medical appointment information."
                )
            },
            {
                "title": "Blood Donor Finder",
                "description": (
                    "A system that helps users find registered "
                    "blood donors based on their requirements."
                )
            },
            {
                "title": "Medical Camp Management System",
                "description": (
                    "A system for managing medical camp registration, "
                    "participants and basic records."
                )
            }
        ],

        "Engineering": [
            {
                "title": "Engineering Project Management System",
                "description": (
                    "A platform for managing student projects, "
                    "tasks, deadlines and team members."
                )
            },
            {
                "title": "Lab Equipment Management System",
                "description": (
                    "A system for tracking laboratory equipment "
                    "and their availability."
                )
            },
            {
                "title": "Student Skill Tracker",
                "description": (
                    "An application that helps engineering students "
                    "track their technical skills and learning progress."
                )
            },
            {
                "title": "College Workshop Manager",
                "description": (
                    "A system for organizing college workshops, "
                    "registrations and schedules."
                )
            },
            {
                "title": "Engineering Resource Portal",
                "description": (
                    "A platform where students can organize and "
                    "access useful academic resources."
                )
            }
        ],

        "Web Development": [
            {
                "title": "Student Resource Portal",
                "description": (
                    "A web platform where students can access "
                    "notes, resources and useful academic links."
                )
            },
            {
                "title": "College Event Management System",
                "description": (
                    "A web application for managing college events "
                    "and student registrations."
                )
            },
            {
                "title": "Online Study Planner",
                "description": (
                    "A web application that helps students create "
                    "study schedules and track tasks."
                )
            },
            {
                "title": "Student Portfolio Builder",
                "description": (
                    "A web application that allows students to "
                    "create and organize professional portfolios."
                )
            },
            {
                "title": "Online Assignment Manager",
                "description": (
                    "A platform for students to organize assignments, "
                    "deadlines and submission status."
                )
            }
        ],

        "IoT": [
            {
                "title": "Smart Classroom System",
                "description": (
                    "An IoT system for monitoring classroom conditions "
                    "and controlling connected devices."
                )
            },
            {
                "title": "Smart Dustbin",
                "description": (
                    "An IoT-based dustbin that detects the level of "
                    "waste and provides status information."
                )
            },
            {
                "title": "Smart Parking System",
                "description": (
                    "A system that detects available parking spaces "
                    "using sensors."
                )
            },
            {
                "title": "Smart Energy Monitor",
                "description": (
                    "An IoT system for monitoring electrical energy usage."
                )
            },
            {
                "title": "Smart Plant Monitoring System",
                "description": (
                    "A system that monitors soil moisture and "
                    "environmental conditions for plants."
                )
            }
        ],

        "Robotics": [
            {
                "title": "Obstacle Avoiding Robot",
                "description": (
                    "A robot that detects obstacles and automatically "
                    "changes direction."
                )
            },
            {
                "title": "Line Following Robot",
                "description": (
                    "A robot that follows a predefined path using sensors."
                )
            },
            {
                "title": "Smart Delivery Robot",
                "description": (
                    "A small robot designed to transport objects "
                    "between predefined locations."
                )
            },
            {
                "title": "Remote Controlled Robot",
                "description": (
                    "A robot that can be controlled remotely using "
                    "a wireless connection."
                )
            },
            {
                "title": "Smart Surveillance Robot",
                "description": (
                    "A mobile robot that captures environmental "
                    "information using sensors and a camera."
                )
            }
        ],

        "Education": [
            {
                "title": "Student Learning Management System",
                "description": (
                    "A platform for organizing courses, learning "
                    "materials and student progress."
                )
            },
            {
                "title": "Online Quiz System",
                "description": (
                    "An application where students can take quizzes "
                    "and view their scores."
                )
            },
            {
                "title": "Study Planner",
                "description": (
                    "An application that helps students plan study "
                    "sessions and track completed topics."
                )
            },
            {
                "title": "Digital Notes Manager",
                "description": (
                    "An application for organizing and accessing "
                    "digital study notes."
                )
            },
            {
                "title": "Student Doubt Management System",
                "description": (
                    "A platform where students can submit academic "
                    "doubts and organize answers."
                )
            }
        ],

        "Agriculture": [
            {
                "title": "Smart Crop Monitoring System",
                "description": (
                    "A system that monitors basic environmental "
                    "conditions affecting crops."
                )
            },
            {
                "title": "Smart Irrigation System",
                "description": (
                    "An automated irrigation system that uses soil "
                    "moisture information to control watering."
                )
            },
            {
                "title": "Crop Disease Information System",
                "description": (
                    "A system that provides information about common "
                    "crop diseases and their management."
                )
            },
            {
                "title": "Farm Resource Management System",
                "description": (
                    "An application for organizing farm resources, "
                    "tasks and crop information."
                )
            },
            {
                "title": "Weather Based Farming Assistant",
                "description": (
                    "An application that provides weather information "
                    "useful for basic farming decisions."
                )
            }
        ]
    }

    return {
        "ideas": backup_ideas.get(
            field,
            backup_ideas["AI"]
        )
    }


# ============================================================
# PROJECT IDEA GENERATOR
# ============================================================

def generate_project_ideas(field: str, level: str):

    prompt = f"""
You are an experienced software engineer and academic project mentor.

Generate project ideas for college students.

Project Field:
{field}

Difficulty Level:
{level}

Generate exactly 5 realistic and useful project ideas.

The projects must be suitable for BE, BTech, BCA, MCA or Diploma students.

Difficulty should be considered internally when generating the ideas.

Beginner:
- Simple projects
- Easy to understand
- Basic concepts
- Suitable for students who are learning programming

Intermediate:
- Moderate complexity
- Multiple useful modules
- APIs, databases or authentication may be used where appropriate

Advanced:
- More complex and innovative projects
- AI, automation, real-time systems, computer vision or advanced APIs may be used when suitable
- Still realistic for a college project

IMPORTANT:

The response for each project must contain ONLY:

1. title
2. description

DO NOT include:

- technologies
- difficulty
- level
- duration
- modules
- skills
- roadmap
- recommendations
- any other fields

Return ONLY valid JSON.

Use exactly this structure:

{{
    "ideas": [
        {{
            "title": "",
            "description": ""
        }}
    ]
}}
"""

    try:

        print("Trying Gemini Project Idea Generator...")

        response = client.models.generate_content(
            model="gemini-3.5-flash",
            contents=prompt,
        )

        text = response.text.strip()

        # Remove Markdown code block
        if text.startswith("```"):
            text = text.replace("```json", "")
            text = text.replace("```", "")
            text = text.strip()

        data = json.loads(text)

        if "ideas" in data and isinstance(data["ideas"], list):

            clean_ideas = []

            for idea in data["ideas"]:

                clean_ideas.append({
                    "title": idea.get(
                        "title",
                        "Untitled Project"
                    ),
                    "description": idea.get(
                        "description",
                        "No description available."
                    )
                })

            print("Gemini Idea Generator successful.")

            return {
                "ideas": clean_ideas
            }

        print("Invalid Gemini idea response.")
        print("Using backup ideas.")

        return get_backup_ideas(field, level)

    except Exception as e:

        print("Gemini Project Idea Error:")
        print(e)

        print("Using BACKUP Project Ideas.")

        return get_backup_ideas(field, level)